spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api
    username: api_db_user
    password: api_db_password
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.json
